package nba

import (
	"github.com/Mahcks/nba-lottery/internal/structures"
)

var Teams []structures.ESPNTeam = []structures.ESPNTeam{
	{
		ID:               "1",
		UID:              "s:40~l:46~t:1",
		Slug:             "atlanta-hawks",
		Abbreviation:     "ATL",
		DisplayName:      "Atlanta Hawks",
		ShortDisplayName: "Hawks",
		Name:             "Hawks",
		Nickname:         "Atlanta",
		Location:         "Atlanta",
		Color:            "002B5C",
		AlternateColor:   "002b5c",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "2",
		UID:              "s:40~l:46~t:2",
		Slug:             "boston-celtics",
		Abbreviation:     "BOS",
		DisplayName:      "Boston Celtics",
		ShortDisplayName: "Celtics",
		Name:             "Celtics",
		Nickname:         "Boston",
		Location:         "Boston",
		Color:            "006532",
		AlternateColor:   "f1f2f3",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "17",
		UID:              "s:40~l:46~t:17",
		Slug:             "brooklyn-nets",
		Abbreviation:     "BKN",
		DisplayName:      "Brooklyn Nets",
		ShortDisplayName: "Nets",
		Name:             "Nets",
		Nickname:         "Brooklyn",
		Location:         "Brooklyn",
		Color:            "000000",
		AlternateColor:   "ffffff",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "30",
		UID:              "s:40~l:46~t:30",
		Slug:             "charlotte-hornets",
		Abbreviation:     "CHA",
		DisplayName:      "Charlotte Hornets",
		ShortDisplayName: "Hornets",
		Name:             "Hornets",
		Nickname:         "Charlotte",
		Location:         "Charlotte",
		Color:            "1D1060",
		AlternateColor:   "008ca8",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "4",
		UID:              "s:40~l:46~t:4",
		Slug:             "chicago-bulls",
		Abbreviation:     "CHI",
		DisplayName:      "Chicago Bulls",
		ShortDisplayName: "Bulls",
		Name:             "Bulls",
		Nickname:         "Chicago",
		Location:         "Chicago",
		Color:            "000000",
		AlternateColor:   "000000",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "5",
		UID:              "s:40~l:46~t:5",
		Slug:             "cleveland-cavaliers",
		Abbreviation:     "CLE",
		DisplayName:      "Cleveland Cavaliers",
		ShortDisplayName: "Cavaliers",
		Name:             "Cavaliers",
		Nickname:         "Cleveland",
		Location:         "Cleveland",
		Color:            "061642",
		AlternateColor:   "fdbb30",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "6",
		UID:              "s:40~l:46~t:6",
		Slug:             "dallas-mavericks",
		Abbreviation:     "DAL",
		DisplayName:      "Dallas Mavericks",
		ShortDisplayName: "Mavericks",
		Name:             "Mavericks",
		Nickname:         "Dallas",
		Location:         "Dallas",
		Color:            "0C479D",
		AlternateColor:   "c4ced3",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "7",
		UID:              "s:40~l:46~t:7",
		Slug:             "denver-nuggets",
		Abbreviation:     "DEN",
		DisplayName:      "Denver Nuggets",
		ShortDisplayName: "Nuggets",
		Name:             "Nuggets",
		Nickname:         "Denver",
		Location:         "Denver",
		Color:            "0860A8",
		AlternateColor:   "fdb927",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "8",
		UID:              "s:40~l:46~t:8",
		Slug:             "detroit-pistons",
		Abbreviation:     "DET",
		DisplayName:      "Detroit Pistons",
		ShortDisplayName: "Pistons",
		Name:             "Pistons",
		Nickname:         "Detroit",
		Location:         "Detroit",
		Color:            "FA002C",
		AlternateColor:   "006bb6",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "9",
		UID:              "s:40~l:46~t:9",
		Slug:             "golden-state-warriors",
		Abbreviation:     "GS",
		DisplayName:      "Golden State Warriors",
		ShortDisplayName: "Warriors",
		Name:             "Warriors",
		Nickname:         "Golden State",
		Location:         "Golden State",
		Color:            "003da5",
		AlternateColor:   "fdb927",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "10",
		UID:              "s:40~l:46~t:10",
		Slug:             "houston-rockets",
		Abbreviation:     "HOU",
		DisplayName:      "Houston Rockets",
		ShortDisplayName: "Rockets",
		Name:             "Rockets",
		Nickname:         "Houston",
		Location:         "Houston",
		Color:            "D40026",
		AlternateColor:   "c4ced3",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "11",
		UID:              "s:40~l:46~t:11",
		Slug:             "indiana-pacers",
		Abbreviation:     "IND",
		DisplayName:      "Indiana Pacers",
		ShortDisplayName: "Pacers",
		Name:             "Pacers",
		Nickname:         "Indiana",
		Location:         "Indiana",
		Color:            "061642",
		AlternateColor:   "00275d",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "12",
		UID:              "s:40~l:46~t:12",
		Slug:             "la-clippers",
		Abbreviation:     "LAC",
		DisplayName:      "LA Clippers",
		ShortDisplayName: "Clippers",
		Name:             "Clippers",
		Nickname:         "LA",
		Location:         "LA",
		Color:            "FA0028",
		AlternateColor:   "f1f2f3",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "13",
		UID:              "s:40~l:46~t:13",
		Slug:             "los-angeles-lakers",
		Abbreviation:     "LAL",
		DisplayName:      "Los Angeles Lakers",
		ShortDisplayName: "Lakers",
		Name:             "Lakers",
		Nickname:         "Los Angeles",
		Location:         "Los Angeles",
		Color:            "542582",
		AlternateColor:   "552582",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "29",
		UID:              "s:40~l:46~t:29",
		Slug:             "memphis-grizzlies",
		Abbreviation:     "MEM",
		DisplayName:      "Memphis Grizzlies",
		ShortDisplayName: "Grizzlies",
		Name:             "Grizzlies",
		Nickname:         "Memphis",
		Location:         "Memphis",
		Color:            "5D76A8",
		AlternateColor:   "7399c6",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "14",
		UID:              "s:40~l:46~t:14",
		Slug:             "miami-heat",
		Abbreviation:     "MIA",
		DisplayName:      "Miami Heat",
		ShortDisplayName: "Heat",
		Name:             "Heat",
		Nickname:         "Miami",
		Location:         "Miami",
		Color:            "000000",
		AlternateColor:   "000000",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "15",
		UID:              "s:40~l:46~t:15",
		Slug:             "milwaukee-bucks",
		Abbreviation:     "MIL",
		DisplayName:      "Milwaukee Bucks",
		ShortDisplayName: "Bucks",
		Name:             "Bucks",
		Nickname:         "Milwaukee",
		Location:         "Milwaukee",
		Color:            "003813",
		AlternateColor:   "f0ebd2",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "16",
		UID:              "s:40~l:46~t:16",
		Slug:             "minnesota-timberwolves",
		Abbreviation:     "MIN",
		DisplayName:      "Minnesota Timberwolves",
		ShortDisplayName: "Timberwolves",
		Name:             "Timberwolves",
		Nickname:         "Minnesota",
		Location:         "Minnesota",
		Color:            "0E3764",
		AlternateColor:   "c4ced3",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "3",
		UID:              "s:40~l:46~t:3",
		Slug:             "new-orleans-pelicans",
		Abbreviation:     "NO",
		DisplayName:      "New Orleans Pelicans",
		ShortDisplayName: "Pelicans",
		Name:             "Pelicans",
		Nickname:         "New Orleans",
		Location:         "New Orleans",
		Color:            "002a5c",
		AlternateColor:   "b4975a",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "18",
		UID:              "s:40~l:46~t:18",
		Slug:             "new-york-knicks",
		Abbreviation:     "NY",
		DisplayName:      "New York Knicks",
		ShortDisplayName: "Knicks",
		Name:             "Knicks",
		Nickname:         "New York",
		Location:         "New York",
		Color:            "225EA8",
		AlternateColor:   "f58426",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "25",
		UID:              "s:40~l:46~t:25",
		Slug:             "oklahoma-city-thunder",
		Abbreviation:     "OKC",
		DisplayName:      "Oklahoma City Thunder",
		ShortDisplayName: "Thunder",
		Name:             "Thunder",
		Nickname:         "Oklahoma City",
		Location:         "Oklahoma City",
		Color:            "C67C03",
		AlternateColor:   "f05133",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "19",
		UID:              "s:40~l:46~t:19",
		Slug:             "orlando-magic",
		Abbreviation:     "ORL",
		DisplayName:      "Orlando Magic",
		ShortDisplayName: "Magic",
		Name:             "Magic",
		Nickname:         "Orlando",
		Location:         "Orlando",
		Color:            "0860A8",
		AlternateColor:   "c4ced3",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "20",
		UID:              "s:40~l:46~t:20",
		Slug:             "philadelphia-76ers",
		Abbreviation:     "PHI",
		DisplayName:      "Philadelphia 76ers",
		ShortDisplayName: "76ers",
		Name:             "76ers",
		Nickname:         "Philadelphia",
		Location:         "Philadelphia",
		Color:            "000000",
		AlternateColor:   "f1f2f3",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "21",
		UID:              "s:40~l:46~t:21",
		Slug:             "phoenix-suns",
		Abbreviation:     "PHX",
		DisplayName:      "Phoenix Suns",
		ShortDisplayName: "Suns",
		Name:             "Suns",
		Nickname:         "Phoenix",
		Location:         "Phoenix",
		Color:            "23006a",
		AlternateColor:   "f1f2f3",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "22",
		UID:              "s:40~l:46~t:22",
		Slug:             "portland-trail-blazers",
		Abbreviation:     "POR",
		DisplayName:      "Portland Trail Blazers",
		ShortDisplayName: "Trail Blazers",
		Name:             "Trail Blazers",
		Nickname:         "Portland",
		Location:         "Portland",
		Color:            "000000",
		AlternateColor:   "bac3c9",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "23",
		UID:              "s:40~l:46~t:23",
		Slug:             "sacramento-kings",
		Abbreviation:     "SAC",
		DisplayName:      "Sacramento Kings",
		ShortDisplayName: "Kings",
		Name:             "Kings",
		Nickname:         "Sacramento",
		Location:         "Sacramento",
		Color:            "393996",
		AlternateColor:   "8e9090",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "24",
		UID:              "s:40~l:46~t:24",
		Slug:             "san-antonio-spurs",
		Abbreviation:     "SA",
		DisplayName:      "San Antonio Spurs",
		ShortDisplayName: "Spurs",
		Name:             "Spurs",
		Nickname:         "San Antonio",
		Location:         "San Antonio",
		Color:            "000000",
		AlternateColor:   "061922",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "28",
		UID:              "s:40~l:46~t:28",
		Slug:             "toronto-raptors",
		Abbreviation:     "TOR",
		DisplayName:      "Toronto Raptors",
		ShortDisplayName: "Raptors",
		Name:             "Raptors",
		Nickname:         "Toronto",
		Location:         "Toronto",
		Color:            "CE0F41",
		AlternateColor:   "061922",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "26",
		UID:              "s:40~l:46~t:26",
		Slug:             "utah-jazz",
		Abbreviation:     "UTAH",
		DisplayName:      "Utah Jazz",
		ShortDisplayName: "Jazz",
		Name:             "Jazz",
		Nickname:         "Utah",
		Location:         "Utah",
		Color:            "000000",
		AlternateColor:   "fff21f",
		IsActive:         true,
		IsAllStar:        false,
	},
	{
		ID:               "27",
		UID:              "s:40~l:46~t:27",
		Slug:             "washington-wizards",
		Abbreviation:     "WSH",
		DisplayName:      "Washington Wizards",
		ShortDisplayName: "Wizards",
		Name:             "Wizards",
		Nickname:         "Washington",
		Location:         "Washington",
		Color:            "0E3764",
		AlternateColor:   "e31837",
		IsActive:         true,
		IsAllStar:        false,
	},
}
