name: build

on:
  pull_request:
  push:

env:
  VERSION: 0.1.3

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          dest: build
          targets: windows/amd64,linux/amd64,darwin/amd64
          v: true
          ldflags: -s -w -X main.Version=${{ VERSION }}
          buildmode: default
          prefix: nba-lottery
      - run: mv build/nba-lottery-windows* build/nba-lottery-windows.exe
      - run: mv build/nba-lottery-darwin* build/nba-lottery-macos
      - run: mv build/nba-lottery-linux* build/nba-lottery-linux
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ VERSION }}
          release_name: v${{ VERSION }} Release - ${{ env.DATE }}
          draft: false
      - name: Upload Windows Asset
        id: upload-release-asset-win 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/nba-lottery-windows.exe
          asset_name: nba-lottery-windows.exe
          asset_content_type: application/x-dosexec
      - name: Upload MacOS Asset
        id: upload-release-asset-mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/nba-lottery-macos
          asset_name: nba-lottery-macos
          asset_content_type: application/x-mach-binary
      - name: Upload Linux Asset
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/nba-lottery-linux
          asset_name: nba-lottery-linux
          asset_content_type: application/x-executable