name: build

on:
  release:
    types: [published]

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          dest: build
          targets: windows/amd64,linux/amd64,darwin/amd64
          v: true
          ldflags: -s -w -X main.Version=${{ github.event.release.tag_name }}
          buildmode: default
          prefix: nba-lottery

      - run: mv build/nba-lottery-windows* build/nba-lottery-windows.exe
      - run: mv build/nba-lottery-darwin* build/nba-lottery-macos
      - run: mv build/nba-lottery-linux* build/nba-lottery-linux

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Edit Release
        id: edit_release
        uses: irongut/EditRelease@v1.2.0
        with:
          id: ${{ github.event.release.id }}
          token: ${{ secrets.GH_TOKEN }}
          name: ${{ github.event.release.tag_name }} Release - ${{ env.DATE }}
          files: "./build/nba-lottery-windows.exe,./build/nba-lottery-macos,./build/nba-lottery-linux"

